// Ingredient categories
// proteins | grains | fruit_veg | dairy | pantry

export const MEAL_INGREDIENTS = {
  // ── BREAKFASTS ──────────────────────────────────────────────────────────────
  b1:  [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Banana",q:1,u:"",c:"fruit_veg"}, {n:"Peanut butter",q:1,u:"tbsp",c:"pantry"} ],
  b2:  [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Frozen berries",q:80,u:"g",c:"fruit_veg"}, {n:"Peanut butter",q:1,u:"tbsp",c:"pantry"} ],
  b3:  [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Apple",q:1,u:"",c:"fruit_veg"}, {n:"Almond butter",q:1,u:"tbsp",c:"pantry"}, {n:"Cinnamon",q:1,u:"tsp",c:"pantry"} ],
  b4:  [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Frozen cherries",q:80,u:"g",c:"fruit_veg"}, {n:"Dark chocolate chips",q:20,u:"g",c:"pantry"} ],
  b5:  [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Mango",q:1,u:"",c:"fruit_veg"}, {n:"Peanut butter",q:1,u:"tbsp",c:"pantry"} ],
  b6:  [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Peach",q:1,u:"",c:"fruit_veg"}, {n:"Almond butter",q:1,u:"tbsp",c:"pantry"} ],
  b7:  [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Strawberries",q:100,u:"g",c:"fruit_veg"}, {n:"Almond butter",q:1,u:"tbsp",c:"pantry"} ],
  b8:  [ {n:"Greek yogurt",q:200,u:"g",c:"dairy"}, {n:"Granola",q:30,u:"g",c:"grains"}, {n:"Frozen berries",q:80,u:"g",c:"fruit_veg"} ],
  b9:  [ {n:"Greek yogurt",q:200,u:"g",c:"dairy"}, {n:"Granola",q:30,u:"g",c:"grains"}, {n:"Banana",q:1,u:"",c:"fruit_veg"}, {n:"Honey",q:1,u:"tsp",c:"pantry"} ],
  b10: [ {n:"Greek yogurt",q:200,u:"g",c:"dairy"}, {n:"Muesli",q:30,u:"g",c:"grains"}, {n:"Kiwi",q:1,u:"",c:"fruit_veg"}, {n:"Chia seeds",q:1,u:"tsp",c:"pantry"} ],
  b11: [ {n:"Greek yogurt",q:200,u:"g",c:"dairy"}, {n:"Granola",q:30,u:"g",c:"grains"}, {n:"Orange",q:1,u:"",c:"fruit_veg"}, {n:"Honey",q:1,u:"tsp",c:"pantry"} ],
  b12: [ {n:"Eggs",q:2,u:"",c:"proteins"}, {n:"Rye crispbreads",q:2,u:"",c:"grains"}, {n:"Tomato",q:1,u:"",c:"fruit_veg"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"} ],
  b13: [ {n:"Eggs",q:2,u:"",c:"proteins"}, {n:"Smoked salmon",q:50,u:"g",c:"proteins"}, {n:"Rye crispbreads",q:2,u:"",c:"grains"}, {n:"Dill",q:1,u:"bunch",c:"fruit_veg"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  b14: [ {n:"Eggs",q:2,u:"",c:"proteins"}, {n:"Avocado",q:0.5,u:"",c:"fruit_veg"}, {n:"Rye crispbreads",q:2,u:"",c:"grains"}, {n:"Chili flakes",q:1,u:"pinch",c:"pantry"} ],
  b15: [ {n:"Eggs",q:2,u:"",c:"proteins"}, {n:"Avocado",q:0.5,u:"",c:"fruit_veg"}, {n:"Rye crispbreads",q:2,u:"",c:"grains"} ],
  b16: [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Frozen berries",q:80,u:"g",c:"fruit_veg"}, {n:"Honey",q:1,u:"tsp",c:"pantry"} ],
  b17: [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Banana",q:1,u:"",c:"fruit_veg"}, {n:"Honey",q:1,u:"tsp",c:"pantry"}, {n:"Cinnamon",q:1,u:"tsp",c:"pantry"} ],
  b18: [ {n:"Rolled oats",q:80,u:"g",c:"grains"}, {n:"Oat milk",q:200,u:"ml",c:"dairy"}, {n:"Pear",q:1,u:"",c:"fruit_veg"}, {n:"Walnuts",q:20,u:"g",c:"pantry"}, {n:"Cinnamon",q:1,u:"tsp",c:"pantry"} ],
  b19: [ {n:"Eggs",q:2,u:"",c:"proteins"}, {n:"Cooked rice",q:150,u:"g",c:"grains"}, {n:"Frozen peas",q:50,u:"g",c:"fruit_veg"}, {n:"Soy sauce",q:1,u:"tbsp",c:"pantry"}, {n:"Sesame oil",q:1,u:"tsp",c:"pantry"} ],

  // ── LUNCHES ─────────────────────────────────────────────────────────────────
  l1:  [ {n:"Chicken breast",q:100,u:"g",c:"proteins"}, {n:"Tortilla wraps",q:1,u:"",c:"grains"}, {n:"Mixed salad leaves",q:40,u:"g",c:"fruit_veg"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"}, {n:"Greek yogurt",q:50,u:"g",c:"dairy"} ],
  l2:  [ {n:"Chicken breast",q:100,u:"g",c:"proteins"}, {n:"Tortilla wraps",q:1,u:"",c:"grains"}, {n:"Romaine lettuce",q:40,u:"g",c:"fruit_veg"}, {n:"Parmesan",q:15,u:"g",c:"dairy"} ],
  l3:  [ {n:"Tortilla wraps",q:1,u:"",c:"grains"}, {n:"Mixed salad leaves",q:30,u:"g",c:"fruit_veg"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"}, {n:"Greek yogurt",q:50,u:"g",c:"dairy"} ],
  l4:  [ {n:"Tuna (canned)",q:1,u:"can",c:"proteins"}, {n:"Rice",q:150,u:"g",c:"grains"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"}, {n:"Avocado",q:0.5,u:"",c:"fruit_veg"}, {n:"Soy sauce",q:1,u:"tbsp",c:"pantry"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  l5:  [ {n:"Tuna (canned)",q:1,u:"can",c:"proteins"}, {n:"Pasta",q:80,u:"g",c:"grains"}, {n:"Cherry tomatoes",q:80,u:"g",c:"fruit_veg"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"} ],
  l6:  [ {n:"Tuna (canned)",q:1,u:"can",c:"proteins"}, {n:"Eggs",q:1,u:"",c:"proteins"}, {n:"Green beans",q:80,u:"g",c:"fruit_veg"}, {n:"Cherry tomatoes",q:80,u:"g",c:"fruit_veg"}, {n:"Black olives",q:30,u:"g",c:"pantry"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  l7:  [ {n:"Tuna (canned)",q:1,u:"can",c:"proteins"}, {n:"Quinoa",q:100,u:"g",c:"grains"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"}, {n:"Cherry tomatoes",q:80,u:"g",c:"fruit_veg"}, {n:"Olive oil",q:1,u:"tbsp",c:"pantry"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  l8:  [ {n:"Smoked salmon",q:100,u:"g",c:"proteins"}, {n:"Eggs",q:1,u:"",c:"proteins"}, {n:"Mixed salad leaves",q:60,u:"g",c:"fruit_veg"}, {n:"Rye crispbreads",q:2,u:"",c:"grains"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  l9:  [ {n:"Smoked salmon",q:80,u:"g",c:"proteins"}, {n:"Tortilla wraps",q:1,u:"",c:"grains"}, {n:"Cream cheese (light)",q:30,u:"g",c:"dairy"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"}, {n:"Dill",q:1,u:"bunch",c:"fruit_veg"} ],
  l10: [ {n:"Smoked salmon",q:100,u:"g",c:"proteins"}, {n:"Mixed salad leaves",q:60,u:"g",c:"fruit_veg"}, {n:"Avocado",q:0.5,u:"",c:"fruit_veg"}, {n:"Capers",q:1,u:"tbsp",c:"pantry"}, {n:"Rye crispbreads",q:2,u:"",c:"grains"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  l11: [ {n:"Smoked mackerel",q:100,u:"g",c:"proteins"}, {n:"Mixed salad leaves",q:60,u:"g",c:"fruit_veg"}, {n:"Potato",q:1,u:"",c:"fruit_veg"}, {n:"Capers",q:1,u:"tbsp",c:"pantry"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  l12: [ {n:"Smoked mackerel",q:100,u:"g",c:"proteins"}, {n:"Tortilla wraps",q:1,u:"",c:"grains"}, {n:"Cream cheese (light)",q:30,u:"g",c:"dairy"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"}, {n:"Dill",q:1,u:"bunch",c:"fruit_veg"} ],
  l13: [ {n:"Cooked prawns",q:100,u:"g",c:"proteins"}, {n:"Mixed salad leaves",q:60,u:"g",c:"fruit_veg"}, {n:"Avocado",q:0.5,u:"",c:"fruit_veg"}, {n:"Cherry tomatoes",q:80,u:"g",c:"fruit_veg"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  l14: [ {n:"Turkey breast",q:100,u:"g",c:"proteins"}, {n:"Pasta",q:80,u:"g",c:"grains"}, {n:"Cherry tomatoes",q:80,u:"g",c:"fruit_veg"}, {n:"Pesto",q:1,u:"tbsp",c:"pantry"}, {n:"Baby spinach",q:40,u:"g",c:"fruit_veg"} ],
  l15: [ {n:"Chicken breast",q:100,u:"g",c:"proteins"}, {n:"Quinoa",q:100,u:"g",c:"grains"}, {n:"Cherry tomatoes",q:80,u:"g",c:"fruit_veg"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"}, {n:"Lemon",q:0.5,u:"",c:"fruit_veg"} ],
  l16: [ {n:"Chickpeas (canned)",q:1,u:"can",c:"proteins"}, {n:"Cherry tomatoes",q:80,u:"g",c:"fruit_veg"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"}, {n:"Red onion",q:0.5,u:"",c:"fruit_veg"}, {n:"Feta cheese",q:50,u:"g",c:"dairy"}, {n:"Olive oil",q:1,u:"tbsp",c:"pantry"} ],
  l17: [ {n:"Chickpeas (canned)",q:1,u:"can",c:"proteins"}, {n:"Baby spinach",q:60,u:"g",c:"fruit_veg"}, {n:"Roasted peppers (jar)",q:60,u:"g",c:"pantry"}, {n:"Feta cheese",q:50,u:"g",c:"dairy"}, {n:"Olive oil",q:1,u:"tbsp",c:"pantry"} ],
  l18: [ {n:"Chickpeas (canned)",q:1,u:"can",c:"proteins"}, {n:"Tortilla wraps",q:1,u:"",c:"grains"}, {n:"Feta cheese",q:40,u:"g",c:"dairy"}, {n:"Baby spinach",q:40,u:"g",c:"fruit_veg"}, {n:"Cherry tomatoes",q:60,u:"g",c:"fruit_veg"} ],
  l19: [ {n:"Lean beef mince",q:100,u:"g",c:"proteins"}, {n:"Garlic",q:2,u:"cloves",c:"fruit_veg"}, {n:"Ginger",q:1,u:"tsp",c:"pantry"}, {n:"Soy sauce",q:2,u:"tbsp",c:"pantry"}, {n:"Iceberg lettuce",q:4,u:"leaves",c:"fruit_veg"} ],
  l20: [ {n:"Red lentils",q:100,u:"g",c:"proteins"}, {n:"Rye bread",q:1,u:"slice",c:"grains"} ],
  l21: [ {n:"Rice",q:100,u:"g",c:"grains"}, {n:"Mixed salad leaves",q:40,u:"g",c:"fruit_veg"} ],
  l22: [ {n:"Rice",q:100,u:"g",c:"grains"}, {n:"Mixed salad leaves",q:40,u:"g",c:"fruit_veg"} ],
  l23: [ {n:"Rice",q:100,u:"g",c:"grains"} ],

  // ── DINNERS ─────────────────────────────────────────────────────────────────
  d1:  [ {n:"Salmon fillet",q:150,u:"g",c:"proteins"}, {n:"Courgette",q:1,u:"",c:"fruit_veg"}, {n:"Bell peppers",q:1,u:"",c:"fruit_veg"}, {n:"Broccoli",q:150,u:"g",c:"fruit_veg"}, {n:"Potato",q:1,u:"",c:"fruit_veg"}, {n:"Olive oil",q:1,u:"tbsp",c:"pantry"} ],
  d2:  [ {n:"Salmon fillet",q:150,u:"g",c:"proteins"}, {n:"Sweet potato",q:1,u:"",c:"fruit_veg"}, {n:"Green beans",q:100,u:"g",c:"fruit_veg"} ],
  d3:  [ {n:"Salmon fillet",q:150,u:"g",c:"proteins"}, {n:"Broccoli",q:200,u:"g",c:"fruit_veg"}, {n:"Rice",q:100,u:"g",c:"grains"}, {n:"Soy sauce",q:2,u:"tbsp",c:"pantry"}, {n:"Garlic",q:2,u:"cloves",c:"fruit_veg"} ],
  d4:  [ {n:"Salmon fillet",q:150,u:"g",c:"proteins"}, {n:"Rice",q:150,u:"g",c:"grains"}, {n:"Edamame",q:80,u:"g",c:"fruit_veg"}, {n:"Teriyaki sauce",q:3,u:"tbsp",c:"pantry"} ],
  d5:  [ {n:"Salmon fillet",q:150,u:"g",c:"proteins"}, {n:"Asparagus",q:150,u:"g",c:"fruit_veg"}, {n:"Rice",q:100,u:"g",c:"grains"}, {n:"Lemon",q:1,u:"",c:"fruit_veg"}, {n:"Olive oil",q:1,u:"tbsp",c:"pantry"} ],
  d6:  [ {n:"Cod fillet",q:150,u:"g",c:"proteins"}, {n:"Courgette",q:1,u:"",c:"fruit_veg"}, {n:"Cherry tomatoes",q:100,u:"g",c:"fruit_veg"}, {n:"Olive oil",q:1,u:"tbsp",c:"pantry"}, {n:"Lemon",q:1,u:"",c:"fruit_veg"} ],
  d7:  [ {n:"Cod fillet",q:150,u:"g",c:"proteins"}, {n:"Sweet potato",q:1,u:"",c:"fruit_veg"}, {n:"Mixed salad leaves",q:60,u:"g",c:"fruit_veg"}, {n:"Lemon",q:1,u:"",c:"fruit_veg"}, {n:"Dill",q:1,u:"bunch",c:"fruit_veg"} ],
  d8:  [ {n:"Cod fillet",q:150,u:"g",c:"proteins"}, {n:"Small tortillas",q:2,u:"",c:"grains"}, {n:"Cabbage",q:100,u:"g",c:"fruit_veg"}, {n:"Lime",q:1,u:"",c:"fruit_veg"}, {n:"Greek yogurt",q:60,u:"g",c:"dairy"} ],
  d9:  [ {n:"Raw prawns",q:150,u:"g",c:"proteins"}, {n:"Frozen stir fry veg",q:200,u:"g",c:"fruit_veg"}, {n:"Noodles",q:80,u:"g",c:"grains"}, {n:"Soy sauce",q:2,u:"tbsp",c:"pantry"}, {n:"Ginger",q:1,u:"tsp",c:"pantry"}, {n:"Garlic",q:2,u:"cloves",c:"fruit_veg"} ],
  d10: [ {n:"Raw prawns",q:150,u:"g",c:"proteins"}, {n:"Light coconut milk",q:200,u:"ml",c:"pantry"}, {n:"Curry paste",q:2,u:"tbsp",c:"pantry"}, {n:"Onion",q:1,u:"",c:"fruit_veg"}, {n:"Bell peppers",q:1,u:"",c:"fruit_veg"}, {n:"Rice",q:150,u:"g",c:"grains"} ],
  d11: [ {n:"Raw prawns",q:150,u:"g",c:"proteins"}, {n:"Rice noodles",q:80,u:"g",c:"grains"}, {n:"Pak choi",q:150,u:"g",c:"fruit_veg"}, {n:"Soy sauce",q:2,u:"tbsp",c:"pantry"}, {n:"Sesame oil",q:1,u:"tsp",c:"pantry"}, {n:"Spring onion",q:2,u:"",c:"fruit_veg"} ],
  d12: [ {n:"Chicken breast",q:120,u:"g",c:"proteins"}, {n:"Frozen stir fry veg",q:200,u:"g",c:"fruit_veg"}, {n:"Rice",q:150,u:"g",c:"grains"}, {n:"Soy sauce",q:2,u:"tbsp",c:"pantry"} ],
  d13: [ {n:"Chicken breast",q:150,u:"g",c:"proteins"}, {n:"Tikka paste",q:2,u:"tbsp",c:"pantry"}, {n:"Rice",q:150,u:"g",c:"grains"}, {n:"Greek yogurt",q:60,u:"g",c:"dairy"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"} ],
  d14: [ {n:"Chicken breast",q:150,u:"g",c:"proteins"}, {n:"Bell peppers",q:2,u:"",c:"fruit_veg"}, {n:"Onion",q:1,u:"",c:"fruit_veg"}, {n:"Fajita spice mix",q:1,u:"tbsp",c:"pantry"}, {n:"Rice",q:150,u:"g",c:"grains"}, {n:"Greek yogurt",q:50,u:"g",c:"dairy"} ],
  d15: [ {n:"Chicken breast",q:100,u:"g",c:"proteins"}, {n:"Baby spinach",q:80,u:"g",c:"fruit_veg"}, {n:"Garlic",q:2,u:"cloves",c:"fruit_veg"}, {n:"Light cream cheese",q:60,u:"g",c:"dairy"}, {n:"Pasta",q:80,u:"g",c:"grains"} ],
  d16: [ {n:"Chicken thighs",q:150,u:"g",c:"proteins"}, {n:"Root veg mix",q:200,u:"g",c:"fruit_veg"}, {n:"Rice",q:100,u:"g",c:"grains"} ],
  d17: [ {n:"Chicken thighs",q:200,u:"g",c:"proteins"}, {n:"Sweet potato",q:1,u:"",c:"fruit_veg"}, {n:"Broccoli",q:150,u:"g",c:"fruit_veg"}, {n:"Garlic",q:3,u:"cloves",c:"fruit_veg"}, {n:"Olive oil",q:1,u:"tbsp",c:"pantry"} ],
  d18: [ {n:"Chicken thighs",q:200,u:"g",c:"proteins"}, {n:"Bell peppers",q:2,u:"",c:"fruit_veg"}, {n:"Onion",q:1,u:"",c:"fruit_veg"}, {n:"Courgette",q:1,u:"",c:"fruit_veg"}, {n:"Potato",q:1,u:"",c:"fruit_veg"}, {n:"Olive oil",q:1,u:"tbsp",c:"pantry"} ],
  d19: [ {n:"Turkey mince",q:100,u:"g",c:"proteins"}, {n:"Pasta",q:80,u:"g",c:"grains"}, {n:"Jarred tomato sauce",q:150,u:"ml",c:"pantry"}, {n:"Baby spinach",q:60,u:"g",c:"fruit_veg"} ],
  d20: [ {n:"Turkey meatballs",q:150,u:"g",c:"proteins"}, {n:"Jarred tomato sauce",q:150,u:"ml",c:"pantry"}, {n:"Pasta",q:80,u:"g",c:"grains"}, {n:"Parmesan",q:15,u:"g",c:"dairy"} ],
  d21: [ {n:"Turkey mince",q:150,u:"g",c:"proteins"}, {n:"Jarred tomato sauce",q:150,u:"ml",c:"pantry"}, {n:"Pasta",q:80,u:"g",c:"grains"}, {n:"Parmesan",q:15,u:"g",c:"dairy"} ],
  d22: [ {n:"Turkey mince",q:150,u:"g",c:"proteins"}, {n:"Kidney beans (canned)",q:1,u:"can",c:"proteins"}, {n:"Canned tomatoes",q:1,u:"can",c:"pantry"}, {n:"Chilli spice mix",q:1,u:"tbsp",c:"pantry"}, {n:"Rice",q:100,u:"g",c:"grains"} ],
  d23: [ {n:"Lean beef mince",q:120,u:"g",c:"proteins"}, {n:"Onion",q:1,u:"",c:"fruit_veg"}, {n:"Garlic",q:2,u:"cloves",c:"fruit_veg"}, {n:"Soy sauce",q:2,u:"tbsp",c:"pantry"}, {n:"Rice",q:150,u:"g",c:"grains"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"} ],
  d24: [ {n:"Lean beef strips",q:120,u:"g",c:"proteins"}, {n:"Frozen stir fry veg",q:200,u:"g",c:"fruit_veg"}, {n:"Noodles",q:80,u:"g",c:"grains"}, {n:"Soy sauce",q:2,u:"tbsp",c:"pantry"}, {n:"Ginger",q:1,u:"tsp",c:"pantry"} ],
  d25: [ {n:"Lean beef strips",q:120,u:"g",c:"proteins"}, {n:"Broccoli",q:200,u:"g",c:"fruit_veg"}, {n:"Garlic",q:2,u:"cloves",c:"fruit_veg"}, {n:"Oyster sauce",q:2,u:"tbsp",c:"pantry"}, {n:"Rice",q:150,u:"g",c:"grains"} ],
  d26: [ {n:"Red lentils",q:150,u:"g",c:"proteins"}, {n:"Onion",q:1,u:"",c:"fruit_veg"}, {n:"Carrot",q:1,u:"",c:"fruit_veg"}, {n:"Canned tomatoes",q:1,u:"can",c:"pantry"}, {n:"Cumin",q:1,u:"tsp",c:"pantry"}, {n:"Rye bread",q:1,u:"slice",c:"grains"} ],
  d27: [ {n:"Red lentils",q:150,u:"g",c:"proteins"}, {n:"Light coconut milk",q:200,u:"ml",c:"pantry"}, {n:"Onion",q:1,u:"",c:"fruit_veg"}, {n:"Garlic",q:2,u:"cloves",c:"fruit_veg"}, {n:"Cumin",q:1,u:"tsp",c:"pantry"}, {n:"Rye bread",q:1,u:"slice",c:"grains"} ],
  d28: [ {n:"Black beans (canned)",q:2,u:"cans",c:"proteins"}, {n:"Onion",q:1,u:"",c:"fruit_veg"}, {n:"Garlic",q:2,u:"cloves",c:"fruit_veg"}, {n:"Smoked paprika",q:1,u:"tsp",c:"pantry"}, {n:"Cumin",q:1,u:"tsp",c:"pantry"}, {n:"Rye bread",q:1,u:"slice",c:"grains"} ],

  // ── SNACKS ──────────────────────────────────────────────────────────────────
  s1:  [ {n:"Apple",q:1,u:"",c:"fruit_veg"}, {n:"Peanut butter",q:1,u:"tbsp",c:"pantry"} ],
  s2:  [ {n:"Apple",q:1,u:"",c:"fruit_veg"}, {n:"Almonds",q:25,u:"g",c:"pantry"} ],
  s3:  [ {n:"Apple",q:1,u:"",c:"fruit_veg"}, {n:"Greek yogurt",q:100,u:"g",c:"dairy"}, {n:"Honey",q:1,u:"tsp",c:"pantry"} ],
  s4:  [ {n:"Banana",q:1,u:"",c:"fruit_veg"}, {n:"Almonds",q:25,u:"g",c:"pantry"} ],
  s5:  [ {n:"Banana",q:1,u:"",c:"fruit_veg"}, {n:"Peanut butter",q:1,u:"tsp",c:"pantry"} ],
  s6:  [ {n:"Almonds",q:25,u:"g",c:"pantry"} ],
  s7:  [ {n:"Greek yogurt",q:150,u:"g",c:"dairy"} ],
  s8:  [ {n:"Greek yogurt",q:150,u:"g",c:"dairy"}, {n:"Honey",q:1,u:"tsp",c:"pantry"} ],
  s9:  [ {n:"Greek yogurt",q:150,u:"g",c:"dairy"}, {n:"Honey",q:1,u:"tsp",c:"pantry"}, {n:"Walnuts",q:20,u:"g",c:"pantry"} ],
  s10: [ {n:"Greek yogurt",q:150,u:"g",c:"dairy"}, {n:"Frozen berries",q:60,u:"g",c:"fruit_veg"} ],
  s11: [ {n:"Greek yogurt",q:150,u:"g",c:"dairy"}, {n:"Frozen berries",q:60,u:"g",c:"fruit_veg"}, {n:"Granola",q:15,u:"g",c:"grains"} ],
  s12: [ {n:"Eggs",q:1,u:"",c:"proteins"}, {n:"Rye crispbreads",q:1,u:"",c:"grains"} ],
  s13: [ {n:"Eggs",q:1,u:"",c:"proteins"}, {n:"Rye crispbreads",q:1,u:"",c:"grains"}, {n:"Cucumber",q:0.5,u:"",c:"fruit_veg"} ],
}

export const CAT_META = {
  proteins:  { label:"Proteins",      emoji:"🥩", color:"#C0392B" },
  grains:    { label:"Grains & Carbs",emoji:"🌾", color:"#C8842A" },
  fruit_veg: { label:"Veg & Fruit",   emoji:"🥦", color:"#3D7A52" },
  dairy:     { label:"Dairy",         emoji:"🥛", color:"#2E5080" },
  pantry:    { label:"Pantry",        emoji:"🥫", color:"#7A3D80" },
}

// Items good for batch cooking on Sunday
export const BATCH_COOK_ITEMS = {
  "Rice":        { task:"Cook large batch of rice", time:"20 min", emoji:"🍚", matches:["Rice","Cooked rice"] },
  "Red lentils": { task:"Cook red lentil soup (makes 3 servings)", time:"25 min", emoji:"🍲", matches:["Red lentils"] },
  "Eggs":        { task:"Boil 6 eggs for the week", time:"10 min", emoji:"🥚", matches:["Eggs"] },
  "Chicken breast": { task:"Grill or bake 3 chicken breasts", time:"25 min", emoji:"🍗", matches:["Chicken breast"] },
  "Quinoa":      { task:"Cook a batch of quinoa", time:"15 min", emoji:"🌾", matches:["Quinoa"] },
  "Pasta":       { task:"Cook pasta (cool and store for cold salads)", time:"12 min", emoji:"🍝", matches:["Pasta"] },
}
